### ISSUE TITLE
WMS GetMap requests fail when version parameter is not specified

### ISSUE THREAD

**Issue by tomkralidis** [camptocamp/ogc-client#47] opened 2024-06-03 15:34 UTC
Testing the [public demo](https://camptocamp.github.io/ogc-client/#/demo) against https://api.weather.gc.ca/geomet yields a GetMap exception from the server, which complains about a missing VERSION parameter.

VERSION is a required OGC WMS GetMap parameter and should be added accordingly.

cc @RousseauLambertLP

**Comment by jahow** [comment] 2024-06-03 15:48
I just tried and reproduced the error, thanks! It fails on the GetCapabilities request:
![image](https://github.com/camptocamp/ogc-client/assets/10629150/b698ff2e-5fed-41b4-a85d-afcc1e4771dc)

Shouldn't the server give back its preferred (i.e. highest) supported version when asking for a GetCapabilities?

**Comment by jahow** [comment] 2024-06-04 08:23
Ok, I reproduced with this URL: https://geo.weather.gc.ca/geomet/?lang=en&service=WMS&request=GetCapabilities

Thanks! I'll work on a fix

**Comment by jahow** [comment] 2024-06-06 21:30
@tomkralidis can you please let me know if the issue is fixed now? thanks!

**Closed** 2024-06-06 21:30 UTC

**Comment by tomkralidis** [comment] 2024-06-06 21:46
confirm, thanks @jahow !
